server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: ${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/